name: Custom Build
on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
      RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_ENV -Append
      - run: python3 .\build.py --flutter
      - uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: flutter/build/windows/x64/runner/Release/
